### ISSUE TITLE
Noob Growth Road

### ISSUE THREAD

**Issue by Gooooe** [mikestock/lwali#1]
Thank you for your advice. I've been learning this code for a while and it does seem to be simpler than INTF, but I still have a few things I don't understand. Both are in the lwa_image.py file
1. Line 197. I don't understand what Wt and W do, W seems to be there to control the frequency band range.
2. Line 241. On get data, I can clearly know that the for loop is to get the data of 6 antennas, but I don't understand the specific meaning of sampleGain and line249 "d*Wt*sampleGain".
3. Line 287. When using fft for cross-correlation, is the xcs[k] finally obtained, each element in it is the offset corresponding to each frequency point? Or can it be understood as the time difference between each point? It is very wise to use fft for cross-correlation, which can effectively speed up the processing.

**Comment by mikestock** [comment]
1.
Wt is time-domain weighting.  When you're imaging, usually you have some amount of time-overlap between subsequent images.   This pushes the power of the resulting image to the activity that happens in the middle of the integration window, and reduces the contribution of activity that happens at the edge.  The Wt is in a class called 'raised cosine' windows, and it looks like I have it set up as a Hamming window.

W selects the frequency band to actually image, and is applied in the frequency domain (the bandwidth is set in the configuration).  In this implementation it's a super simple top-hat filter (it's on or off), and with the LWA can probably be neglected.  But, you can use the same construct to apply filters or whiten the data as well.  Looks like I do some whitening on line 283 as well

2. 
sampleGain comes from the tbf_to_timeseries.py program.  It's there so I can convert the resulting time-series into 16bit integers, and retain maximum definition for each channel.  I'm not sure why I'm multiplying it by 1000 though, that seems a bit hacky.

3. 
xcs are the cross correlation values, the array is in lag-time (time domain).  In the calculation, you can see that we're taking the inverse FFT (ifft) of pairs of frequency domain data.  Because we calculated the cross correlation using FFTs, the output is wrapped kinda funny.  0 lag is at the beginning of the array, but negative lags are at the end counting backwards.  I use negative indices to be able to access those.

**Comment by Gooooe** [comment]
Many belated thanks! 

To be honest, before this, I didn't know what top hat filtering was, after I checked the relevant information. I understood, and it dawned on me. The top hat transform is used for bright objects on dark backgrounds, which is awesome!

I'm currently creating some random numbers to better understand the code. yeah~
I'm learning more stuff and it's fun!

**Comment by Gooooe** [comment]
Good evening, sorry to disturb you. 

In the lwa_render.py file.
Line 92. Why leave only data divisible by 10 to plot?

Line 94. Why transpose the imFrame matrix and then add 1？

Hope you are well.

**Comment by mikestock** [comment]
Line 92. the imager produced an image for every single time period.  But,
the renderer is adding N of them together before making a frame.  If N is
1, that will render at maximum time resolution, and the resulting animation
will be very very very slow.  N=10 will reduce the rate by a factor of 10,
around 100k fps.

Line 94. I want to display the image on a log scale, but the image has 0's
in it and the log of 0 is -inf.  To keep things well behaved, I just add 1
to the image.  The transpose is related to the location of the image
origin, and the location of the array origin, they tend not to be the
same.

Michael Stock
http://lightning-interferometry.com

**Comment by Gooooe** [comment]
Thank you very much. I'll check it carefully
Wish you a happy life!
